CC=gcc
CFLAGS=-Wall -g

A:
	$(CC) $(CFLAGS) A-Store-Credit.c -o A-Store-Credit

B:
	$(CC) $(CFLAGS) B-Reverse-Words.c -o B-Reverse-Words

# Touch the files to prevent error if they don't exist
clean:
	touch A-Store-Credit B-Reverse-Words
	rm A-Store-Credit B-Reverse-Words
